export interface Question {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation?: string;
}

export const questions: Question[] = [
  {
    id: 1,
    question: "What will be the output of: print(type(5.5))",
    options: ["<class 'int'>", "<class 'float'>", "<class 'str'>", "<class 'number'>"],
    correctAnswer: 1,
  },
  {
    id: 2,
    question: "What is the result of: int('10.5')?",
    options: ["10", "10.5", "Error", "'10.5'"],
    correctAnswer: 2,
  },
  {
    id: 3,
    question: "What will print(3 + '5') output?",
    options: ["8", "'35'", "Error", "None"],
    correctAnswer: 2,
  },
  {
    id: 4,
    question: "What is str(42)?",
    options: ["42", "'42'", "int", "Error"],
    correctAnswer: 1,
  },
  {
    id: 5,
    question: "Which of the following is a mutable data type in Python?",
    options: ["tuple", "string", "list", "int"],
    correctAnswer: 2,
  },
  {
    id: 6,
    question: "What will this code output? x = 5; print(x if x > 3 else 'small')",
    options: ["5", "'5'", "small", "Error"],
    correctAnswer: 0,
  },
  {
    id: 7,
    question: "What is the output of: print('hello' * 3)?",
    options: ["'hello * 3'", "'hellohellohello'", "hellohellohello", "Error"],
    correctAnswer: 2,
  },
  {
    id: 8,
    question: "What will this code print? if 5 > 3: print('yes') else: print('no')",
    options: ["yes", "no", "Error", "None"],
    correctAnswer: 0,
  },
  {
    id: 9,
    question: "What is the output of: print(bool(0))?",
    options: ["True", "False", "0", "Error"],
    correctAnswer: 1,
  },
  {
    id: 10,
    question: "What does this code output? x = [1, 2, 3]; print(x[-1])",
    options: ["1", "2", "3", "Error"],
    correctAnswer: 2,
  },
  {
    id: 11,
    question: "What is the length of this list? [1, 'a', 3.5, [4, 5]]",
    options: ["5", "4", "3", "Error"],
    correctAnswer: 1,
  },
  {
    id: 12,
    question: "What will this code output? for i in range(3): print(i)",
    options: ["0 1 2", "0\\n1\\n2", "1 2 3", "3 2 1"],
    correctAnswer: 1,
  },
  {
    id: 13,
    question: "What is the output of: dict({'a': 1, 'b': 2}).get('c', 'default')?",
    options: ["None", "'default'", "KeyError", "Error"],
    correctAnswer: 1,
  },
  {
    id: 14,
    question: "What will this code output? d = {'x': 10}; d['x'] += 5; print(d['x'])",
    options: ["5", "10", "15", "Error"],
    correctAnswer: 2,
  },
  {
    id: 15,
    question: "What is the output of: len('hello')?",
    options: ["4", "5", "6", "Error"],
    correctAnswer: 1,
  },
  {
    id: 16,
    question: "What will this function return? def func(a, b=5): return a + b; func(3)?",
    options: ["3", "5", "8", "Error"],
    correctAnswer: 2,
  },
  {
    id: 17,
    question: "What is the output of: print(10 // 3)?",
    options: ["3", "3.33", "3.0", "Error"],
    correctAnswer: 0,
  },
  {
    id: 18,
    question: "What will this code output? print(10 % 3)",
    options: ["1", "3", "7", "Error"],
    correctAnswer: 0,
  },
  {
    id: 19,
    question: "What is the result of: 'hello'.upper()?",
    options: ["'HELLO'", "HELLO", "'hello'", "Error"],
    correctAnswer: 0,
  },
  {
    id: 20,
    question: "What will this code output? x = [1, 2, 3]; x.append(4); print(len(x))",
    options: ["3", "4", "5", "Error"],
    correctAnswer: 1,
  },
  {
    id: 21,
    question: "What is the output of: print(type([]))?",
    options: ["<class 'list'>", "<class 'array'>", "<class 'tuple'>", "<class 'dict'>"],
    correctAnswer: 0,
  },
  {
    id: 22,
    question: "What will this code output? y = 5; y = y ** 2; print(y)",
    options: ["10", "25", "5", "Error"],
    correctAnswer: 1,
  },
  {
    id: 23,
    question: "What is the output of: 'abc'.find('b')?",
    options: ["'b'", "1", "2", "0"],
    correctAnswer: 1,
  },
  {
    id: 24,
    question: "What will this dictionary do? d = {}; d[1] = 'a'; d[2] = 'b'; print(len(d))",
    options: ["1", "2", "3", "Error"],
    correctAnswer: 1,
  },
  {
    id: 25,
    question: "What is the output of: print([1, 2] + [3, 4])?",
    options: ["[5]", "[1, 2, 3, 4]", "Error", "[6]"],
    correctAnswer: 1,
  },
  {
    id: 26,
    question: "What will this code output? x = 'hello'; print(x[1:4])",
    options: ["'h'", "'hell'", "'ell'", "'ello'"],
    correctAnswer: 2,
  },
  {
    id: 27,
    question: "What is the output of: print(bool(''))?",
    options: ["True", "False", "None", "Error"],
    correctAnswer: 1,
  },
  {
    id: 28,
    question: "What will this code output? for i in range(1, 4): print(i)",
    options: ["1\\n2\\n3\\n4", "1\\n2\\n3", "0\\n1\\n2\\n3", "Error"],
    correctAnswer: 1,
  },
  {
    id: 29,
    question: "What is the result of: tuple([1, 2, 3])?",
    options: ["[1, 2, 3]", "(1, 2, 3)", "Error", "'1, 2, 3'"],
    correctAnswer: 1,
  },
  {
    id: 30,
    question: "What will this code output? def add(*args): return sum(args); add(1, 2, 3)?",
    options: ["[1, 2, 3]", "6", "'123'", "Error"],
    correctAnswer: 1,
  },
  {
    id: 31,
    question: "What is the output of: print(5 == 5.0)?",
    options: ["True", "False", "None", "Error"],
    correctAnswer: 0,
  },
  {
    id: 32,
    question: "What will this code output? x = 10; if x > 5: if x > 15: print('big') else: print('mid')",
    options: ["big", "mid", "Error", "None"],
    correctAnswer: 1,
  },
  {
    id: 33,
    question: "What is the output of: 'hello'.replace('l', 'L')?",
    options: ["'heLLo'", "'heLlo'", "Error", "'hello'"],
    correctAnswer: 0,
  },
  {
    id: 34,
    question: "What will this code output? d = {'a': [1, 2, 3]}; print(len(d['a']))",
    options: ["1", "3", "2", "Error"],
    correctAnswer: 1,
  },
  {
    id: 35,
    question: "What is the result of: list('abc')?",
    options: ["['abc']", "['a', 'b', 'c']", "'abc'", "Error"],
    correctAnswer: 1,
  },
  {
    id: 36,
    question: "What will this code output? x = [1, 2, 3]; y = x; y.append(4); print(x)",
    options: ["[1, 2, 3]", "[1, 2, 3, 4]", "Error", "None"],
    correctAnswer: 1,
  },
  {
    id: 37,
    question: "What is the output of: print(type(None))?",
    options: ["<class 'NoneType'>", "<class 'none'>", "<class 'null'>", "Error"],
    correctAnswer: 0,
  },
  {
    id: 38,
    question: "What will this code output? s = 'python'; print(s[::2])",
    options: ["'pto'", "'yhn'", "'ptn'", "'yto'"],
    correctAnswer: 0,
  },
  {
    id: 39,
    question: "What is the result of: max([3, 1, 4, 1, 5])?",
    options: ["1", "4", "5", "Error"],
    correctAnswer: 2,
  },
  {
    id: 40,
    question: "What will this code output? x = {1, 2, 3, 2}; print(len(x))",
    options: ["4", "3", "2", "Error"],
    correctAnswer: 1,
  },
  {
    id: 41,
    question: "What is the output of: sorted([3, 1, 2])?",
    options: ["[3, 1, 2]", "[1, 2, 3]", "Error", "(1, 2, 3)"],
    correctAnswer: 1,
  },
  {
    id: 42,
    question: "What will this code output? def f(x): return x * 2; print(f(5))",
    options: ["5", "7", "10", "Error"],
    correctAnswer: 2,
  },
  {
    id: 43,
    question: "What is the result of: ' hello '.strip()?",
    options: ["' hello '", "'hello'", "Error", "'hello '"],
    correctAnswer: 1,
  },
  {
    id: 44,
    question: "What will this code output? x = 0; while x < 3: x += 1; print(x)",
    options: ["0", "1", "2", "3"],
    correctAnswer: 3,
  },
  {
    id: 45,
    question: "What is the output of: print(ord('A'))?",
    options: ["'65'", "65", "'A'", "Error"],
    correctAnswer: 1,
  },
  {
    id: 46,
    question: "What will this code output? d = {1: 'a', 2: 'b'}; print(list(d.keys()))",
    options: ["['a', 'b']", "[1, 2]", "Error", "['1', '2']"],
    correctAnswer: 1,
  },
  {
    id: 47,
    question: "What is the result of: isinstance(5, int)?",
    options: ["True", "False", "Error", "5"],
    correctAnswer: 0,
  },
  {
    id: 48,
    question: "What will this code output? x = [1, 2, 3]; x = x * 2; print(x)",
    options: ["[1, 2, 3]", "[2, 4, 6]", "[1, 2, 3, 1, 2, 3]", "Error"],
    correctAnswer: 2,
  },
  {
    id: 49,
    question: "What is the output of: sum([1, 2, 3, 4])?",
    options: ["'1234'", "10", "4", "Error"],
    correctAnswer: 1,
  },
  {
    id: 50,
    question: "What will this code output? def func(**kwargs): return len(kwargs); func(a=1, b=2, c=3)?",
    options: ["3", "6", "Error", "'abc'"],
    correctAnswer: 0,
  },
];
